#!/bin/bash

#
# Delete all certificates
#
echo "Delete all certificate"
printf "AT+NWDCRT\x0d\x0a" > /dev/ttyS8

sleep 5

#
# MQTT Root CA certificate
#
echo "Installing MQTT Root CA certificate"
printf '\x1bC0,-----BEGIN CERTIFICATE-----\nMIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ\nRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD\nVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX\nDTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y\nZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy\nVHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr\nmD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr\nIZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK\nmpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu\nXmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy\ndc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/ye\njl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1\nBE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3\nDQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92\n9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx\njkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0\nEpn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz\nksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLS\nR9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp\n-----END CERTIFICATE-----\n\x03\x0d\x0a' > /dev/ttyS8

sleep 2

#
# HTTP Root CA certificate
#
echo "Installing HTTP Root CA certificate"
printf '\x1bC3,-----BEGIN CERTIFICATE-----\nMIIByzCCAXACAQEwCgYIKoZIzj0EAwIwczELMAkGA1UEBhMCVUsxEDAOBgNVBAgM\nB0JyaXN0b2wxEDAOBgNVBAcMB0JyaXN0b2wxEDAOBgNVBAoMB1dpdGVraW8xEDAO\nBgNVBAsMB0JyaXN0b2wxHDAaBgNVBAMME1VLQnJpc3RvbFdpdGVraW9ORE0wIBcN\nMjMwNjA2MTQ0OTMxWhgPMjA1MDEwMjExNDQ5MzFaMHAxCzAJBgNVBAYTAlVLMRAw\nDgYDVQQIDAdCcmlzdG9sMRAwDgYDVQQHDAdCcmlzdG9sMRAwDgYDVQQKDAdXaXRl\na2lvMRAwDgYDVQQLDAdCcmlzdG9sMRkwFwYDVQQDDBBhdnRkcy14NTA5ZGV2aWNl\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJSSSLBrIyBe4TJgKC4pwjn/ZWoNH1CU2\ndFXHuHj3UYiUJyrZ2P/cMWmOeWQDxBwCUxwiuJ6lr714bkmbVSFZMzAKBggqhkjO\nPQQDAgNJADBGAiEAx2ixvk+8jvpHG0c3xt4IY6vky9DNzcixNYKQihqDUb4CIQDG\nHGBV/JfCuOj1fFIdVZbF/dJQTOzy4GIYuLnO8Z0L9A==\n-----END CERTIFICATE-----\n\x03\x0d\x0a' > /dev/ttyS8

sleep 2

#
# MQTT device certificate
#
echo "Installing MQTT device certificate"
printf '\x1bC1,-----BEGIN CERTIFICATE-----\nMIIByzCCAXACAQEwCgYIKoZIzj0EAwIwczELMAkGA1UEBhMCVUsxEDAOBgNVBAgM\nB0JyaXN0b2wxEDAOBgNVBAcMB0JyaXN0b2wxEDAOBgNVBAoMB1dpdGVraW8xEDAO\nBgNVBAsMB0JyaXN0b2wxHDAaBgNVBAMME1VLQnJpc3RvbFdpdGVraW9ORE0wIBcN\nMjMwNjA2MTQ0OTMxWhgPMjA1MDEwMjExNDQ5MzFaMHAxCzAJBgNVBAYTAlVLMRAw\nDgYDVQQIDAdCcmlzdG9sMRAwDgYDVQQHDAdCcmlzdG9sMRAwDgYDVQQKDAdXaXRl\na2lvMRAwDgYDVQQLDAdCcmlzdG9sMRkwFwYDVQQDDBBhdnRkcy14NTA5ZGV2aWNl\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJSSSLBrIyBe4TJgKC4pwjn/ZWoNH1CU2\ndFXHuHj3UYiUJyrZ2P/cMWmOeWQDxBwCUxwiuJ6lr714bkmbVSFZMzAKBggqhkjO\nPQQDAgNJADBGAiEAx2ixvk+8jvpHG0c3xt4IY6vky9DNzcixNYKQihqDUb4CIQDG\nHGBV/JfCuOj1fFIdVZbF/dJQTOzy4GIYuLnO8Z0L9A==\n-----END CERTIFICATE-----\n\x03\x0d\x0a' > /dev/ttyS8

sleep 2

#
# MQTT device private key
#
echo "Installing MQTT device private key"
printf '\x1bC2,-----BEGIN EC PRIVATE KEY-----\nMHQCAQEEIA/3tFBwrmgBY491Rpdv60Cp4wt+MVFejSa+5U+jlS+HoAcGBSuBBAAK\noUQDQgAEJSSSLBrIyBe4TJgKC4pwjn/ZWoNH1CU2dFXHuHj3UYiUJyrZ2P/cMWmO\neWQDxBwCUxwiuJ6lr714bkmbVSFZMw==\n-----END EC PRIVATE KEY-----\n\x03\x0d\x0a' > /dev/ttyS8

sleep 2

echo "AT+NWICCPID avtds" > /dev/ttyS8
echo "AT+NWICENV avnetpoc" > /dev/ttyS8
echo "AT+NWICAT 5" > /dev/ttyS8
echo "AT+NWICDUID x509device" > /dev/ttyS8
echo "AT+NWICSYNC 0" > /dev/ttyS8

sleep 4

echo "AT+NWICSYNC 1" > /dev/ttyS8

sleep 4

printf "AT+NWMQMSG=car,red,type,bus,height,2\x0d\x0a"
