cleanall:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(OBJS)
	-$(RM) $(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS) *.a *.elf *.bin *.map
	-$(RM) ../img/*.img
	-$(RM) "${SDKRootDirPath}/tools/SBOOT/image/"*RTOS.bin
	-$(RM) "${SDKRootDirPath}/tools/SBOOT/public/"*RTOS.img
	-@echo ' '